name: deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 18
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew clean && ./gradlew build && ./gradlew jar
      - name: Copy jar to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "./build/libs/PythonS-1.0.jar,./Dockerfile,./docker-compose.yaml"
          target: "piss/"
          strip_components: 1
      - name: Deployment on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            chmod +x deploypiss.sh
            ./deploypiss.sh
